/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v5.0
processor: MKL27Z256xxx4
package_id: MKL27Z256VFM4
mcu_data: ksdk2_0
processor_version: 5.0.0
pin_labels:
- {pin_num: '30', pin_signal: ADC0_SE6b/PTD5/SPI1_SCK/UART2_TX/TPM0_CH5/FXIO0_D5, label: LED1, identifier: LED1}
- {pin_num: '31', pin_signal: ADC0_SE7b/PTD6/LLWU_P15/SPI1_MOSI/LPUART0_RX/SPI1_MISO/FXIO0_D6, label: LED2, identifier: LED2}
- {pin_num: '32', pin_signal: PTD7/SPI1_MISO/LPUART0_TX/SPI1_MOSI/FXIO0_D7, label: LED3, identifier: LED3}
- {pin_num: '24', pin_signal: PTC3/LLWU_P7/SPI1_SCK/LPUART1_RX/TPM0_CH2/CLKOUT/I2S0_TX_BCLK, label: CS_LIS, identifier: CS_LIS}
- {pin_num: '25', pin_signal: PTC4/LLWU_P8/SPI0_SS/LPUART1_TX/TPM0_CH3/I2S0_MCLK, label: CS_LPS, identifier: CS_LPS}
- {pin_num: '29', pin_signal: PTD4/LLWU_P14/SPI1_SS/UART2_RX/TPM0_CH4/FXIO0_D4, label: CS_FLASH, identifier: CS_FLASH}
- {pin_num: '12', pin_signal: PTA2/LPUART0_TX/TPM2_CH1, label: BUZZER, identifier: BUZZER}
- {pin_num: '11', pin_signal: PTA1/LPUART0_RX/TPM2_CH0, label: SWITCH, identifier: SWITCH}
- {pin_num: '18', pin_signal: XTAL0/PTA19/LPUART1_TX/TPM_CLKIN1/LPTMR0_ALT1, label: OLED_RST, identifier: OLED_RST}
- {pin_num: '1', pin_signal: PTE0/CLKOUT32K/SPI1_MISO/LPUART1_TX/RTC_CLKOUT/CMP0_OUT/I2C1_SDA, label: PWR_SW, identifier: PWR_SW}
- {pin_num: '9', pin_signal: DAC0_OUT/ADC0_SE23/CMP0_IN4/PTE30/TPM0_CH3/TPM_CLKIN1/LPUART1_TX/LPTMR0_ALT1, label: VBAT, identifier: VBAT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '30', peripheral: GPIOD, signal: 'GPIO, 5', pin_signal: ADC0_SE6b/PTD5/SPI1_SCK/UART2_TX/TPM0_CH5/FXIO0_D5, direction: OUTPUT, gpio_init_state: 'true',
    slew_rate: slow}
  - {pin_num: '31', peripheral: GPIOD, signal: 'GPIO, 6', pin_signal: ADC0_SE7b/PTD6/LLWU_P15/SPI1_MOSI/LPUART0_RX/SPI1_MISO/FXIO0_D6, direction: OUTPUT, gpio_init_state: 'true',
    slew_rate: slow, drive_strength: high}
  - {pin_num: '32', peripheral: GPIOD, signal: 'GPIO, 7', pin_signal: PTD7/SPI1_MISO/LPUART0_TX/SPI1_MOSI/FXIO0_D7, direction: OUTPUT, gpio_init_state: 'true', slew_rate: slow,
    drive_strength: high}
  - {pin_num: '13', peripheral: SWD, signal: DIO, pin_signal: PTA3/I2C1_SCL/TPM0_CH0/SWD_DIO}
  - {pin_num: '10', peripheral: SWD, signal: CLK, pin_signal: PTA0/TPM0_CH5/SWD_CLK}
  - {pin_num: '24', peripheral: GPIOC, signal: 'GPIO, 3', pin_signal: PTC3/LLWU_P7/SPI1_SCK/LPUART1_RX/TPM0_CH2/CLKOUT/I2S0_TX_BCLK, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '25', peripheral: GPIOC, signal: 'GPIO, 4', pin_signal: PTC4/LLWU_P8/SPI0_SS/LPUART1_TX/TPM0_CH3/I2S0_MCLK, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '29', peripheral: GPIOD, signal: 'GPIO, 4', pin_signal: PTD4/LLWU_P14/SPI1_SS/UART2_RX/TPM0_CH4/FXIO0_D4, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '26', peripheral: SPI0, signal: SCK, pin_signal: PTC5/LLWU_P9/SPI0_SCK/LPTMR0_ALT2/I2S0_RXD0/CMP0_OUT}
  - {pin_num: '27', peripheral: SPI0, signal: MOSI, pin_signal: CMP0_IN0/PTC6/LLWU_P10/SPI0_MOSI/EXTRG_IN/I2S0_RX_BCLK/SPI0_MISO/I2S0_MCLK}
  - {pin_num: '28', peripheral: SPI0, signal: MISO, pin_signal: CMP0_IN1/PTC7/SPI0_MISO/USB_SOF_OUT/I2S0_RX_FS/SPI0_MOSI}
  - {pin_num: '20', peripheral: I2C0, signal: SCL, pin_signal: ADC0_SE8/PTB0/LLWU_P5/I2C0_SCL/TPM1_CH0}
  - {pin_num: '21', peripheral: I2C0, signal: SDA, pin_signal: ADC0_SE9/PTB1/I2C0_SDA/TPM1_CH1}
  - {pin_num: '9', peripheral: ADC0, signal: 'SE, 23', pin_signal: DAC0_OUT/ADC0_SE23/CMP0_IN4/PTE30/TPM0_CH3/TPM_CLKIN1/LPUART1_TX/LPTMR0_ALT1}
  - {pin_num: '11', peripheral: GPIOA, signal: 'GPIO, 1', pin_signal: PTA1/LPUART0_RX/TPM2_CH0, direction: INPUT, pull_select: up}
  - {pin_num: '12', peripheral: TPM2, signal: 'CH, 1', pin_signal: PTA2/LPUART0_TX/TPM2_CH1}
  - {pin_num: '18', peripheral: GPIOA, signal: 'GPIO, 19', pin_signal: XTAL0/PTA19/LPUART1_TX/TPM_CLKIN1/LPTMR0_ALT1, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '1', peripheral: GPIOE, signal: 'GPIO, 0', pin_signal: PTE0/CLKOUT32K/SPI1_MISO/LPUART1_TX/RTC_CLKOUT/CMP0_OUT/I2C1_SDA, direction: OUTPUT, gpio_init_state: 'true',
    slew_rate: slow}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Port B Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);
    /* Port C Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortC);
    /* Port D Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortD);
    /* Port E Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortE);

    gpio_pin_config_t SWITCH_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA1 (pin 11)  */
    GPIO_PinInit(BOARD_INITPINS_SWITCH_GPIO, BOARD_INITPINS_SWITCH_PIN, &SWITCH_config);

    gpio_pin_config_t OLED_RST_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTA19 (pin 18)  */
    GPIO_PinInit(BOARD_INITPINS_OLED_RST_GPIO, BOARD_INITPINS_OLED_RST_PIN, &OLED_RST_config);

    gpio_pin_config_t CS_LIS_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTC3 (pin 24)  */
    GPIO_PinInit(BOARD_INITPINS_CS_LIS_GPIO, BOARD_INITPINS_CS_LIS_PIN, &CS_LIS_config);

    gpio_pin_config_t CS_LPS_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTC4 (pin 25)  */
    GPIO_PinInit(BOARD_INITPINS_CS_LPS_GPIO, BOARD_INITPINS_CS_LPS_PIN, &CS_LPS_config);

    gpio_pin_config_t CS_FLASH_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTD4 (pin 29)  */
    GPIO_PinInit(BOARD_INITPINS_CS_FLASH_GPIO, BOARD_INITPINS_CS_FLASH_PIN, &CS_FLASH_config);

    gpio_pin_config_t LED1_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTD5 (pin 30)  */
    GPIO_PinInit(BOARD_INITPINS_LED1_GPIO, BOARD_INITPINS_LED1_PIN, &LED1_config);

    gpio_pin_config_t LED2_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTD6 (pin 31)  */
    GPIO_PinInit(BOARD_INITPINS_LED2_GPIO, BOARD_INITPINS_LED2_PIN, &LED2_config);

    gpio_pin_config_t LED3_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTD7 (pin 32)  */
    GPIO_PinInit(BOARD_INITPINS_LED3_GPIO, BOARD_INITPINS_LED3_PIN, &LED3_config);

    gpio_pin_config_t PWR_SW_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTE0 (pin 1)  */
    GPIO_PinInit(BOARD_INITPINS_PWR_SW_GPIO, BOARD_INITPINS_PWR_SW_PIN, &PWR_SW_config);

    /* PORTA0 (pin 10) is configured as SWD_CLK */
    PORT_SetPinMux(PORTA, 0U, kPORT_MuxAlt7);

    /* PORTA1 (pin 11) is configured as PTA1 */
    PORT_SetPinMux(BOARD_INITPINS_SWITCH_PORT, BOARD_INITPINS_SWITCH_PIN, kPORT_MuxAsGpio);

    PORTA->PCR[1] = ((PORTA->PCR[1] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | PORT_PCR_PS(kPORT_PullUp));

    /* PORTA19 (pin 18) is configured as PTA19 */
    PORT_SetPinMux(BOARD_INITPINS_OLED_RST_PORT, BOARD_INITPINS_OLED_RST_PIN, kPORT_MuxAsGpio);

    /* PORTA2 (pin 12) is configured as TPM2_CH1 */
    PORT_SetPinMux(BOARD_INITPINS_BUZZER_PORT, BOARD_INITPINS_BUZZER_PIN, kPORT_MuxAlt3);

    /* PORTA3 (pin 13) is configured as SWD_DIO */
    PORT_SetPinMux(PORTA, 3U, kPORT_MuxAlt7);

    /* PORTB0 (pin 20) is configured as I2C0_SCL */
    PORT_SetPinMux(PORTB, 0U, kPORT_MuxAlt2);

    /* PORTB1 (pin 21) is configured as I2C0_SDA */
    PORT_SetPinMux(PORTB, 1U, kPORT_MuxAlt2);

    /* PORTC3 (pin 24) is configured as PTC3 */
    PORT_SetPinMux(BOARD_INITPINS_CS_LIS_PORT, BOARD_INITPINS_CS_LIS_PIN, kPORT_MuxAsGpio);

    /* PORTC4 (pin 25) is configured as PTC4 */
    PORT_SetPinMux(BOARD_INITPINS_CS_LPS_PORT, BOARD_INITPINS_CS_LPS_PIN, kPORT_MuxAsGpio);

    /* PORTC5 (pin 26) is configured as SPI0_SCK */
    PORT_SetPinMux(PORTC, 5U, kPORT_MuxAlt2);

    /* PORTC6 (pin 27) is configured as SPI0_MOSI */
    PORT_SetPinMux(PORTC, 6U, kPORT_MuxAlt2);

    /* PORTC7 (pin 28) is configured as SPI0_MISO */
    PORT_SetPinMux(PORTC, 7U, kPORT_MuxAlt2);

    /* PORTD4 (pin 29) is configured as PTD4 */
    PORT_SetPinMux(BOARD_INITPINS_CS_FLASH_PORT, BOARD_INITPINS_CS_FLASH_PIN, kPORT_MuxAsGpio);

    /* PORTD5 (pin 30) is configured as PTD5 */
    PORT_SetPinMux(BOARD_INITPINS_LED1_PORT, BOARD_INITPINS_LED1_PIN, kPORT_MuxAsGpio);

    PORTD->PCR[5] = ((PORTD->PCR[5] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_SRE_MASK | PORT_PCR_ISF_MASK)))

                     /* Slew Rate Enable: Slow slew rate is configured on the corresponding pin, if the pin is
                      * configured as a digital output. */
                     | PORT_PCR_SRE(kPORT_SlowSlewRate));

    /* PORTD6 (pin 31) is configured as PTD6 */
    PORT_SetPinMux(BOARD_INITPINS_LED2_PORT, BOARD_INITPINS_LED2_PIN, kPORT_MuxAsGpio);

    PORTD->PCR[6] = ((PORTD->PCR[6] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_SRE_MASK | PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                     /* Slew Rate Enable: Slow slew rate is configured on the corresponding pin, if the pin is
                      * configured as a digital output. */
                     | PORT_PCR_SRE(kPORT_SlowSlewRate)

                     /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if pin
                      * is configured as a digital output. */
                     | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTD7 (pin 32) is configured as PTD7 */
    PORT_SetPinMux(BOARD_INITPINS_LED3_PORT, BOARD_INITPINS_LED3_PIN, kPORT_MuxAsGpio);

    PORTD->PCR[7] = ((PORTD->PCR[7] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_SRE_MASK | PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                     /* Slew Rate Enable: Slow slew rate is configured on the corresponding pin, if the pin is
                      * configured as a digital output. */
                     | PORT_PCR_SRE(kPORT_SlowSlewRate)

                     /* Drive Strength Enable: High drive strength is configured on the corresponding pin, if pin
                      * is configured as a digital output. */
                     | PORT_PCR_DSE(kPORT_HighDriveStrength));

    /* PORTE0 (pin 1) is configured as PTE0 */
    PORT_SetPinMux(BOARD_INITPINS_PWR_SW_PORT, BOARD_INITPINS_PWR_SW_PIN, kPORT_MuxAsGpio);

    PORTE->PCR[0] = ((PORTE->PCR[0] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_SRE_MASK | PORT_PCR_ISF_MASK)))

                     /* Slew Rate Enable: Slow slew rate is configured on the corresponding pin, if the pin is
                      * configured as a digital output. */
                     | PORT_PCR_SRE(kPORT_SlowSlewRate));

    /* PORTE30 (pin 9) is configured as ADC0_SE23 */
    PORT_SetPinMux(BOARD_INITPINS_VBAT_PORT, BOARD_INITPINS_VBAT_PIN, kPORT_PinDisabledOrAnalog);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
