/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORTD5 (number 30), LED1
  @{ */
#define BOARD_INITPINS_LED1_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_LED1_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_LED1_PIN 5U     /*!<@brief PORTD pin index: 5 */
                                       /* @} */

/*! @name PORTD6 (number 31), LED2
  @{ */
#define BOARD_INITPINS_LED2_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_LED2_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_LED2_PIN 6U     /*!<@brief PORTD pin index: 6 */
                                       /* @} */

/*! @name PORTD7 (number 32), LED3
  @{ */
#define BOARD_INITPINS_LED3_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_LED3_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_LED3_PIN 7U     /*!<@brief PORTD pin index: 7 */
                                       /* @} */

/*! @name PORTC3 (number 24), CS_LIS
  @{ */
#define BOARD_INITPINS_CS_LIS_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_CS_LIS_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_CS_LIS_PIN 3U     /*!<@brief PORTC pin index: 3 */
                                         /* @} */

/*! @name PORTC4 (number 25), CS_LPS
  @{ */
#define BOARD_INITPINS_CS_LPS_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_CS_LPS_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_CS_LPS_PIN 4U     /*!<@brief PORTC pin index: 4 */
                                         /* @} */

/*! @name PORTD4 (number 29), CS_FLASH
  @{ */
#define BOARD_INITPINS_CS_FLASH_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_CS_FLASH_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_CS_FLASH_PIN 4U     /*!<@brief PORTD pin index: 4 */
                                           /* @} */

/*! @name PORTE30 (number 9), VBAT
  @{ */
#define BOARD_INITPINS_VBAT_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_VBAT_PIN 30U    /*!<@brief PORTE pin index: 30 */
                                       /* @} */

/*! @name PORTA1 (number 11), SWITCH
  @{ */
#define BOARD_INITPINS_SWITCH_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_SWITCH_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_SWITCH_PIN 1U     /*!<@brief PORTA pin index: 1 */
                                         /* @} */

/*! @name PORTA2 (number 12), BUZZER
  @{ */
#define BOARD_INITPINS_BUZZER_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_BUZZER_PIN 2U     /*!<@brief PORTA pin index: 2 */
                                         /* @} */

/*! @name PORTA19 (number 18), OLED_RST
  @{ */
#define BOARD_INITPINS_OLED_RST_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_OLED_RST_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_OLED_RST_PIN 19U    /*!<@brief PORTA pin index: 19 */
                                           /* @} */

/*! @name PORTE0 (number 1), PWR_SW
  @{ */
#define BOARD_INITPINS_PWR_SW_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_PWR_SW_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_PWR_SW_PIN 0U     /*!<@brief PORTE pin index: 0 */
                                         /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
